# Generated by Django 5.2.12 on 2026-03-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
