# Generated by Django 5.2.12 on 2026-03-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(default=None, max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
