sequenceDiagram
    participant browser
    participant server

    Note right of browser: User types a note and clicks Save button

    browser->>server: POST /exampleapp/new_note
    activate server
    Note left of server: Server processes the form data and saves the new data
    server->>browser: Redirect to /notes
    deactivate server

    browser->>server: GET /notes
    activate server
    server->>browser: Notes HTML Document
    deactivate server

    browser->>server: GET /main.css
    activate server
    server->>browser: CSS file
    deactivate server

    browser->>server: GET /main.js
    activate server
    server->>browser: JS file
    deactivate server

    Note right of browser: The browser executes the JS and fetches the JSON from server

    browser->>server: GET /data.json
    activate server
    server->>browser: Data JSON
    deactivate server
    
    Note right of browser: The browser executes the callback function that renders the notes